version: '3.7'
services:
  api:
    build:
      context: .
    command: >
      uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    volumes:
      - ./src:/app
